### ISSUE TITLE
跑不起来，这个不维护了吗

### ISSUE THREAD

**Issue by ouzhou** [umijs/next-app#20]
![image](https://user-images.githubusercontent.com/7693866/94016882-4bd5e780-fde1-11ea-9cc2-1b96afd02816.png)

**Comment by sorrycc** [comment]
@xiaohuoni 如果优先级低，可以把仓库 archive 下。

**Comment by xiaohuoni** [comment]
消息太多了，没看到这个。我处理一下，乾坤升级了。

**Comment by xiaohuoni** [comment]
@ouzhou 修复了。我只维护了 009qiankun 和 master 分支，如果其他子分支有错误，再提醒我修复下。
