### ISSUE TITLE
@umijs/plugin-antd dark: true 报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/next-app#7]
Failed to compile with 1 errors              21:33:08

 error  in ./node_modules/@umijs/plugin-layout/lib/component/Exception/index.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

**Comment by chenshuai2144** [comment]
我自己打自己

**Comment by kaoding** [comment]
这种尝试很好
step by step

**Comment by xiaohuoni** [comment]
已修复
