### ISSUE TITLE
@umijs/plugin-locale 国际化，antd 日期组件，没有变化

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/next-app#9]
![image](https://user-images.githubusercontent.com/11746742/78998465-41010080-7b7b-11ea-9486-6fabe664c4fe.png)

**Comment by chenshuai2144** [comment]
别的组件呢？只有日期有问题吗？

**Comment by xiaohuoni** [comment]
日历组件也一样的问题

**Comment by xiaohuoni** [comment]
@xiaohuoni 请优先看这个问题。
